### ISSUE TITLE
Headers changed in Realm 0.91

### ISSUE THREAD

**Issue by cvermilion** [nerdishbynature/NBNRealmBrowser#2]
When I build with NBNRealmBrowser against Realm 0.91.1, I get a bunch of import errors -- looks like `RLMProperty` and `RLMObjectSchema` aren't included by `#import <Realm/Realm.h>` any more.

**Comment by pietbrauer** [comment]
PR #3 fixes this. Can you confirm?

**Comment by cvermilion** [comment]
Looks good to me -- thanks!
